In [2]:
import pandas as pd
df = pd.read_csv('Data/game/game_data.csv',encoding='gbk')
df.head(3)

,基站ID,省份代码,省,地市代码,地市,严重卡顿局数占比,总局数,日卡顿用户数,卡顿集中时段,数据报表日期
0,460_01_33043_118100257,81,四川,28,成都,0,12,0,18,20180221
1,460_01_33045_118669089,81,四川,28,成都,0,15,0,12,20180221
2,460_01_33042_118208288,81,四川,28,成都,0,8,0,18,20180221

In [3]:
df.describe()

,省份代码,地市代码,严重卡顿局数占比,总局数,日卡顿用户数,卡顿集中时段,数据报表日期
count,52839,52839.000000,52839.000000,52839.000000,52839.000000,52839.000000,52839
mean,81,638.471678,0.016721,23.437877,0.297735,16.263745,20180221
std,0,338.084403,0.050723,24.740693,0.722268,5.288956,0
min,81,28.000000,0.000000,5.000000,0.000000,0.000000,20180221
25%,81,812.000000,0.000000,9.000000,0.000000,13.000000,20180221
50%,81,818.000000,0.000000,15.000000,0.000000,16.000000,20180221
75%,81,831.000000,0.000000,29.000000,0.000000,21.000000,20180221
max,81,839.000000,1.000000,504.000000,19.000000,23.000000,20180221

In [4]:
print (df.groupby('地市').size())

地市
乐山           1872
内江           2044
凉山彝族自治州      2011
南充           5194
宜宾           4280
巴中           2532
广元           1798
广安           3106
德阳           1445
成都           8552
攀枝花           957
泸州           2758
甘孜藏族自治州       268
眉山           1695
绵阳           2700
自贡           1577
资阳           2151
达州           4491
遂宁           2280
阿坝藏族羌族自治州     341
雅安            787
dtype: int64

In [5]:
df['总局数大于70'] = df['总局数'] > 70
df['严重卡顿局数占比大于0.07'] = df['严重卡顿局数占比'] > 0.07

In [6]:
df.head(5)

,基站ID,省份代码,省,地市代码,地市,严重卡顿局数占比,总局数,日卡顿用户数,卡顿集中时段,数据报表日期,总局数大于70,严重卡顿局数占比大于0.07
0,460_01_33043_118100257,81,四川,28,成都,0,12,0,18,20180221,False,False
1,460_01_33045_118669089,81,四川,28,成都,0,15,0,12,20180221,False,False
2,460_01_33042_118208288,81,四川,28,成都,0,8,0,18,20180221,False,False
3,460_01_33042_245644034,81,四川,28,成都,0,6,0,13,20180221,False,False
4,460_01_33045_117907743,81,四川,28,成都,0,10,0,19,20180221,False,False

In [7]:
df1=df.loc[df["总局数大于70"] == True]   #单列筛选方法
df1.head()

,基站ID,省份代码,省,地市代码,地市,严重卡顿局数占比,总局数,日卡顿用户数,卡顿集中时段,数据报表日期,总局数大于70,严重卡顿局数占比大于0.07
23,460_01_33076_118121503,81,四川,28,成都,0.0390,77,2,11,20180221,True,False
70,460_01_33046_245414691,81,四川,28,成都,0.0000,193,0,2,20180221,True,False
94,460_01_33192_122715424,81,四川,28,成都,0.0000,73,0,16,20180221,True,False
122,460_01_33034_117705503,81,四川,28,成都,0.0333,90,2,16,20180221,True,False
154,460_01_33047_118405407,81,四川,28,成都,0.0000,83,0,13,20180221,True,False

In [8]:
df2=df.loc[(df["总局数大于70"] == True)&(df["严重卡顿局数占比大于0.07"] == True)]   #多列筛选方法
df2.head()

,基站ID,省份代码,省,地市代码,地市,严重卡顿局数占比,总局数,日卡顿用户数,卡顿集中时段,数据报表日期,总局数大于70,严重卡顿局数占比大于0.07
2354,460_01_33034_117719556,81,四川,28,成都,0.1183,93,8,17,20180221,True,True
3491,460_01_33276_123287857,81,四川,813,自贡,0.0948,116,5,13,20180221,True,True
3530,460_01_33037_117760032,81,四川,28,成都,0.1096,73,3,14,20180221,True,True
5474,460_01_33207_123831584,81,四川,839,广元,0.0779,77,2,9,20180221,True,True
7583,460_01_33181_122650912,81,四川,838,德阳,0.0714,98,2,15,20180221,True,True

In [9]:
df2.groupby('地市').size()

地市
乐山          3
凉山彝族自治州     3
南充          8
宜宾          3
巴中          8
广元          2
广安         25
德阳          5
成都          2
泸州          1
甘孜藏族自治州     1
绵阳          2
自贡          1
达州         65
dtype: int64

In [10]:
df2.groupby('卡顿集中时段').sum()['总局数']

卡顿集中时段
0           74
8          660
9          400
10         809
11         702
12         964
13        1189
14        1088
15         808
16        1124
17         888
18         453
19        1165
20        1026
21        1512
22         871
23         690
Name: 总局数, dtype: int64

In [11]:
df.groupby('卡顿集中时段').sum()['总局数']

卡顿集中时段
0          24096
1          10957
2           6713
3           2791
4           2247
5           1402
6           1972
7           4125
8          14833
9          34046
10         60214
11         81961
12         61093
13         69813
14         71936
15         67408
16        175591
17         63249
18         56550
19         64164
20         80015
21         91998
22         85910
23        105350
Name: 总局数, dtype: int64